// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cmd/ptt/server/proto/ptt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentTitles []string               `protobuf:"bytes,1,rep,name=torrent_titles,json=torrentTitles,proto3" json:"torrent_titles,omitempty"`
	Normalize     bool                   `protobuf:"varint,2,opt,name=normalize,proto3" json:"normalize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_cmd_ptt_server_proto_ptt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_ptt_server_proto_ptt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_cmd_ptt_server_proto_ptt_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetTorrentTitles() []string {
	if x != nil {
		return x.TorrentTitles
	}
	return nil
}

func (x *ParseRequest) GetNormalize() bool {
	if x != nil {
		return x.Normalize
	}
	return false
}

type ParseResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*ParseResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_cmd_ptt_server_proto_ptt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_ptt_server_proto_ptt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_cmd_ptt_server_proto_ptt_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetResults() []*ParseResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type ParseResponse_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         []string               `protobuf:"bytes,1,rep,name=audio,proto3" json:"audio,omitempty"`
	BitDepth      string                 `protobuf:"bytes,2,opt,name=bit_depth,json=bitDepth,proto3" json:"bit_depth,omitempty"`
	Channels      []string               `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`
	Commentary    bool                   `protobuf:"varint,5,opt,name=commentary,proto3" json:"commentary,omitempty"`
	Complete      bool                   `protobuf:"varint,6,opt,name=complete,proto3" json:"complete,omitempty"`
	Container     string                 `protobuf:"bytes,7,opt,name=container,proto3" json:"container,omitempty"`
	Convert       bool                   `protobuf:"varint,8,opt,name=convert,proto3" json:"convert,omitempty"`
	Date          string                 `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
	Documentary   bool                   `protobuf:"varint,10,opt,name=documentary,proto3" json:"documentary,omitempty"`
	Dubbed        bool                   `protobuf:"varint,11,opt,name=dubbed,proto3" json:"dubbed,omitempty"`
	Edition       string                 `protobuf:"bytes,12,opt,name=edition,proto3" json:"edition,omitempty"`
	EpisodeCode   string                 `protobuf:"bytes,13,opt,name=episode_code,json=episodeCode,proto3" json:"episode_code,omitempty"`
	Episodes      []int32                `protobuf:"varint,14,rep,packed,name=episodes,proto3" json:"episodes,omitempty"`
	Extended      bool                   `protobuf:"varint,15,opt,name=extended,proto3" json:"extended,omitempty"`
	Extension     string                 `protobuf:"bytes,16,opt,name=extension,proto3" json:"extension,omitempty"`
	Group         string                 `protobuf:"bytes,17,opt,name=group,proto3" json:"group,omitempty"`
	Hdr           []string               `protobuf:"bytes,18,rep,name=hdr,proto3" json:"hdr,omitempty"`
	Hardcoded     bool                   `protobuf:"varint,19,opt,name=hardcoded,proto3" json:"hardcoded,omitempty"`
	Languages     []string               `protobuf:"bytes,20,rep,name=languages,proto3" json:"languages,omitempty"`
	Network       string                 `protobuf:"bytes,21,opt,name=network,proto3" json:"network,omitempty"`
	Proper        bool                   `protobuf:"varint,22,opt,name=proper,proto3" json:"proper,omitempty"`
	Quality       string                 `protobuf:"bytes,23,opt,name=quality,proto3" json:"quality,omitempty"`
	ReleaseTypes  []string               `protobuf:"bytes,24,rep,name=release_types,json=releaseTypes,proto3" json:"release_types,omitempty"`
	Region        string                 `protobuf:"bytes,25,opt,name=region,proto3" json:"region,omitempty"`
	Remastered    bool                   `protobuf:"varint,26,opt,name=remastered,proto3" json:"remastered,omitempty"`
	Repack        bool                   `protobuf:"varint,27,opt,name=repack,proto3" json:"repack,omitempty"`
	Resolution    string                 `protobuf:"bytes,28,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Retail        bool                   `protobuf:"varint,29,opt,name=retail,proto3" json:"retail,omitempty"`
	Seasons       []int32                `protobuf:"varint,30,rep,packed,name=seasons,proto3" json:"seasons,omitempty"`
	Site          string                 `protobuf:"bytes,31,opt,name=site,proto3" json:"site,omitempty"`
	Size          string                 `protobuf:"bytes,32,opt,name=size,proto3" json:"size,omitempty"`
	Subbed        bool                   `protobuf:"varint,33,opt,name=subbed,proto3" json:"subbed,omitempty"`
	ThreeD        string                 `protobuf:"bytes,34,opt,name=three_d,json=threeD,proto3" json:"three_d,omitempty"`
	Title         string                 `protobuf:"bytes,35,opt,name=title,proto3" json:"title,omitempty"`
	Uncensored    bool                   `protobuf:"varint,36,opt,name=uncensored,proto3" json:"uncensored,omitempty"`
	Unrated       bool                   `protobuf:"varint,37,opt,name=unrated,proto3" json:"unrated,omitempty"`
	Upscaled      bool                   `protobuf:"varint,38,opt,name=upscaled,proto3" json:"upscaled,omitempty"`
	Volumes       []int32                `protobuf:"varint,39,rep,packed,name=volumes,proto3" json:"volumes,omitempty"`
	Year          string                 `protobuf:"bytes,40,opt,name=year,proto3" json:"year,omitempty"`
	Err           string                 `protobuf:"bytes,41,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse_Result) Reset() {
	*x = ParseResponse_Result{}
	mi := &file_cmd_ptt_server_proto_ptt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse_Result) ProtoMessage() {}

func (x *ParseResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_ptt_server_proto_ptt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse_Result.ProtoReflect.Descriptor instead.
func (*ParseResponse_Result) Descriptor() ([]byte, []int) {
	return file_cmd_ptt_server_proto_ptt_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ParseResponse_Result) GetAudio() []string {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *ParseResponse_Result) GetBitDepth() string {
	if x != nil {
		return x.BitDepth
	}
	return ""
}

func (x *ParseResponse_Result) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ParseResponse_Result) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *ParseResponse_Result) GetCommentary() bool {
	if x != nil {
		return x.Commentary
	}
	return false
}

func (x *ParseResponse_Result) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *ParseResponse_Result) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ParseResponse_Result) GetConvert() bool {
	if x != nil {
		return x.Convert
	}
	return false
}

func (x *ParseResponse_Result) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ParseResponse_Result) GetDocumentary() bool {
	if x != nil {
		return x.Documentary
	}
	return false
}

func (x *ParseResponse_Result) GetDubbed() bool {
	if x != nil {
		return x.Dubbed
	}
	return false
}

func (x *ParseResponse_Result) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

func (x *ParseResponse_Result) GetEpisodeCode() string {
	if x != nil {
		return x.EpisodeCode
	}
	return ""
}

func (x *ParseResponse_Result) GetEpisodes() []int32 {
	if x != nil {
		return x.Episodes
	}
	return nil
}

func (x *ParseResponse_Result) GetExtended() bool {
	if x != nil {
		return x.Extended
	}
	return false
}

func (x *ParseResponse_Result) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *ParseResponse_Result) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ParseResponse_Result) GetHdr() []string {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (x *ParseResponse_Result) GetHardcoded() bool {
	if x != nil {
		return x.Hardcoded
	}
	return false
}

func (x *ParseResponse_Result) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *ParseResponse_Result) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ParseResponse_Result) GetProper() bool {
	if x != nil {
		return x.Proper
	}
	return false
}

func (x *ParseResponse_Result) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *ParseResponse_Result) GetReleaseTypes() []string {
	if x != nil {
		return x.ReleaseTypes
	}
	return nil
}

func (x *ParseResponse_Result) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ParseResponse_Result) GetRemastered() bool {
	if x != nil {
		return x.Remastered
	}
	return false
}

func (x *ParseResponse_Result) GetRepack() bool {
	if x != nil {
		return x.Repack
	}
	return false
}

func (x *ParseResponse_Result) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *ParseResponse_Result) GetRetail() bool {
	if x != nil {
		return x.Retail
	}
	return false
}

func (x *ParseResponse_Result) GetSeasons() []int32 {
	if x != nil {
		return x.Seasons
	}
	return nil
}

func (x *ParseResponse_Result) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *ParseResponse_Result) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ParseResponse_Result) GetSubbed() bool {
	if x != nil {
		return x.Subbed
	}
	return false
}

func (x *ParseResponse_Result) GetThreeD() string {
	if x != nil {
		return x.ThreeD
	}
	return ""
}

func (x *ParseResponse_Result) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ParseResponse_Result) GetUncensored() bool {
	if x != nil {
		return x.Uncensored
	}
	return false
}

func (x *ParseResponse_Result) GetUnrated() bool {
	if x != nil {
		return x.Unrated
	}
	return false
}

func (x *ParseResponse_Result) GetUpscaled() bool {
	if x != nil {
		return x.Upscaled
	}
	return false
}

func (x *ParseResponse_Result) GetVolumes() []int32 {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *ParseResponse_Result) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *ParseResponse_Result) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_cmd_ptt_server_proto_ptt_proto protoreflect.FileDescriptor

const file_cmd_ptt_server_proto_ptt_proto_rawDesc = "" +
	"\n" +
	"\x1ecmd/ptt/server/proto/ptt.proto\x12\aexample\"S\n" +
	"\fParseRequest\x12%\n" +
	"\x0etorrent_titles\x18\x01 \x03(\tR\rtorrentTitles\x12\x1c\n" +
	"\tnormalize\x18\x02 \x01(\bR\tnormalize\"\x89\t\n" +
	"\rParseResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.example.ParseResponse.ResultR\aresults\x1a\xbe\b\n" +
	"\x06Result\x12\x14\n" +
	"\x05audio\x18\x01 \x03(\tR\x05audio\x12\x1b\n" +
	"\tbit_depth\x18\x02 \x01(\tR\bbitDepth\x12\x1a\n" +
	"\bchannels\x18\x03 \x03(\tR\bchannels\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x12\x1e\n" +
	"\n" +
	"commentary\x18\x05 \x01(\bR\n" +
	"commentary\x12\x1a\n" +
	"\bcomplete\x18\x06 \x01(\bR\bcomplete\x12\x1c\n" +
	"\tcontainer\x18\a \x01(\tR\tcontainer\x12\x18\n" +
	"\aconvert\x18\b \x01(\bR\aconvert\x12\x12\n" +
	"\x04date\x18\t \x01(\tR\x04date\x12 \n" +
	"\vdocumentary\x18\n" +
	" \x01(\bR\vdocumentary\x12\x16\n" +
	"\x06dubbed\x18\v \x01(\bR\x06dubbed\x12\x18\n" +
	"\aedition\x18\f \x01(\tR\aedition\x12!\n" +
	"\fepisode_code\x18\r \x01(\tR\vepisodeCode\x12\x1a\n" +
	"\bepisodes\x18\x0e \x03(\x05R\bepisodes\x12\x1a\n" +
	"\bextended\x18\x0f \x01(\bR\bextended\x12\x1c\n" +
	"\textension\x18\x10 \x01(\tR\textension\x12\x14\n" +
	"\x05group\x18\x11 \x01(\tR\x05group\x12\x10\n" +
	"\x03hdr\x18\x12 \x03(\tR\x03hdr\x12\x1c\n" +
	"\thardcoded\x18\x13 \x01(\bR\thardcoded\x12\x1c\n" +
	"\tlanguages\x18\x14 \x03(\tR\tlanguages\x12\x18\n" +
	"\anetwork\x18\x15 \x01(\tR\anetwork\x12\x16\n" +
	"\x06proper\x18\x16 \x01(\bR\x06proper\x12\x18\n" +
	"\aquality\x18\x17 \x01(\tR\aquality\x12#\n" +
	"\rrelease_types\x18\x18 \x03(\tR\freleaseTypes\x12\x16\n" +
	"\x06region\x18\x19 \x01(\tR\x06region\x12\x1e\n" +
	"\n" +
	"remastered\x18\x1a \x01(\bR\n" +
	"remastered\x12\x16\n" +
	"\x06repack\x18\x1b \x01(\bR\x06repack\x12\x1e\n" +
	"\n" +
	"resolution\x18\x1c \x01(\tR\n" +
	"resolution\x12\x16\n" +
	"\x06retail\x18\x1d \x01(\bR\x06retail\x12\x18\n" +
	"\aseasons\x18\x1e \x03(\x05R\aseasons\x12\x12\n" +
	"\x04site\x18\x1f \x01(\tR\x04site\x12\x12\n" +
	"\x04size\x18  \x01(\tR\x04size\x12\x16\n" +
	"\x06subbed\x18! \x01(\bR\x06subbed\x12\x17\n" +
	"\athree_d\x18\" \x01(\tR\x06threeD\x12\x14\n" +
	"\x05title\x18# \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"uncensored\x18$ \x01(\bR\n" +
	"uncensored\x12\x18\n" +
	"\aunrated\x18% \x01(\bR\aunrated\x12\x1a\n" +
	"\bupscaled\x18& \x01(\bR\bupscaled\x12\x18\n" +
	"\avolumes\x18' \x03(\x05R\avolumes\x12\x12\n" +
	"\x04year\x18( \x01(\tR\x04year\x12\x10\n" +
	"\x03err\x18) \x01(\tR\x03err2F\n" +
	"\n" +
	"PTTService\x128\n" +
	"\x05Parse\x12\x15.example.ParseRequest\x1a\x16.example.ParseResponse\"\x00B4Z2github.com/MunifTanjim/go-ptt/cmd/ptt/server/protob\x06proto3"

var (
	file_cmd_ptt_server_proto_ptt_proto_rawDescOnce sync.Once
	file_cmd_ptt_server_proto_ptt_proto_rawDescData []byte
)

func file_cmd_ptt_server_proto_ptt_proto_rawDescGZIP() []byte {
	file_cmd_ptt_server_proto_ptt_proto_rawDescOnce.Do(func() {
		file_cmd_ptt_server_proto_ptt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_ptt_server_proto_ptt_proto_rawDesc), len(file_cmd_ptt_server_proto_ptt_proto_rawDesc)))
	})
	return file_cmd_ptt_server_proto_ptt_proto_rawDescData
}

var file_cmd_ptt_server_proto_ptt_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_ptt_server_proto_ptt_proto_goTypes = []any{
	(*ParseRequest)(nil),         // 0: example.ParseRequest
	(*ParseResponse)(nil),        // 1: example.ParseResponse
	(*ParseResponse_Result)(nil), // 2: example.ParseResponse.Result
}
var file_cmd_ptt_server_proto_ptt_proto_depIdxs = []int32{
	2, // 0: example.ParseResponse.results:type_name -> example.ParseResponse.Result
	0, // 1: example.PTTService.Parse:input_type -> example.ParseRequest
	1, // 2: example.PTTService.Parse:output_type -> example.ParseResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_ptt_server_proto_ptt_proto_init() }
func file_cmd_ptt_server_proto_ptt_proto_init() {
	if File_cmd_ptt_server_proto_ptt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_ptt_server_proto_ptt_proto_rawDesc), len(file_cmd_ptt_server_proto_ptt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_ptt_server_proto_ptt_proto_goTypes,
		DependencyIndexes: file_cmd_ptt_server_proto_ptt_proto_depIdxs,
		MessageInfos:      file_cmd_ptt_server_proto_ptt_proto_msgTypes,
	}.Build()
	File_cmd_ptt_server_proto_ptt_proto = out.File
	file_cmd_ptt_server_proto_ptt_proto_goTypes = nil
	file_cmd_ptt_server_proto_ptt_proto_depIdxs = nil
}
